import React, { useState, useEffect } from 'react';
import { db } from '../services/db';
import { SheepStatus, Sheep } from '../types';
import { Filter, Plus, ScanLine, MoreHorizontal, Edit, Trash2, Search } from 'lucide-react';
import { Modal } from '../components/Modal';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

export const SheepManager: React.FC = () => {
  const [sheepList, setSheepList] = useState<Sheep[]>([]);
  const [filter, setFilter] = useState<SheepStatus | 'ALL'>('ALL');
  const [search, setSearch] = useState('');
  const [selectedSheepId, setSelectedSheepId] = useState<string | null>(null);
  
  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [formData, setFormData] = useState<Partial<Sheep>>({});

  useEffect(() => {
    loadSheep();
  }, []);

  const loadSheep = async () => {
    const data = await db.getSheep();
    setSheepList(data);
    // Select first sheep by default if none selected
    if (!selectedSheepId && data.length > 0) setSelectedSheepId(data[0].id);
  };

  const activeSheepData = sheepList.find(s => s.id === selectedSheepId);

  const handleOpenAdd = () => {
    setEditMode(false);
    setFormData({
      status: SheepStatus.HEALTHY,
      gender: 'Male',
      weightHistory: [],
      imageUrl: `https://picsum.photos/400/300?random=${Math.floor(Math.random()*100)}`
    });
    setIsModalOpen(true);
  };

  const handleOpenEdit = (sheep: Sheep) => {
    setEditMode(true);
    setFormData(sheep);
    setIsModalOpen(true);
  };

  const handleDelete = async (id: string) => {
    if (confirm('Are you sure you want to remove this sheep? This action cannot be undone.')) {
      await db.deleteSheep(id);
      await loadSheep();
      if (selectedSheepId === id) setSelectedSheepId(null);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const sheepData = formData as Sheep;
    
    // Ensure basic fields are present
    if (!sheepData.tagId || !sheepData.breed) return alert('Tag ID and Breed are required');

    if (editMode) {
      await db.updateSheep(sheepData);
    } else {
      await db.addSheep({
        ...sheepData,
        id: '', // Will be generated by DB
        weightHistory: [{ date: new Date().toISOString().split('T')[0], weight: 0 }]
      });
    }
    
    setIsModalOpen(false);
    loadSheep();
  };

  const filteredSheep = sheepList
    .filter(s => filter === 'ALL' || s.status === filter)
    .filter(s => s.tagId.toLowerCase().includes(search.toLowerCase()) || s.breed.toLowerCase().includes(search.toLowerCase()));

  return (
    <div className="space-y-6 h-[calc(100vh-8rem)] flex flex-col">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-800">Sheep Inventory</h1>
          <p className="text-slate-500 text-sm">Manage {sheepList.length} total heads of livestock.</p>
        </div>
        <div className="flex gap-2 w-full sm:w-auto">
          <div className="relative flex-1 sm:w-64">
             <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
             <input 
              type="text" 
              placeholder="Search Tag ID..." 
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              className="w-full pl-9 pr-4 py-2 bg-white border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-agri-500"
            />
          </div>
          <button 
            onClick={handleOpenAdd}
            className="flex items-center gap-2 bg-agri-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-agri-700 shadow-sm"
          >
            <Plus size={16} /> <span className="hidden sm:inline">Add Sheep</span>
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 flex-1 min-h-0">
        {/* List Section */}
        <div className="lg:col-span-2 bg-white rounded-xl shadow-sm border border-slate-100 flex flex-col overflow-hidden">
          <div className="flex items-center gap-2 p-4 border-b border-slate-100 overflow-x-auto">
             {['ALL', 'Healthy', 'Sick', 'Sold'].map(status => (
               <button
                key={status}
                onClick={() => setFilter(status as any)}
                className={`px-3 py-1.5 rounded-full text-xs font-medium whitespace-nowrap transition-colors ${
                  filter === status ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
                }`}
               >
                 {status}
               </button>
             ))}
          </div>
          
          <div className="overflow-auto flex-1">
            <table className="w-full text-sm text-left">
              <thead className="bg-slate-50 text-slate-500 font-medium sticky top-0 z-10">
                <tr>
                  <th className="px-6 py-3">Tag ID</th>
                  <th className="px-6 py-3">Breed</th>
                  <th className="px-6 py-3">Cage</th>
                  <th className="px-6 py-3">Status</th>
                  <th className="px-6 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredSheep.map((sheep) => (
                  <tr 
                    key={sheep.id} 
                    onClick={() => setSelectedSheepId(sheep.id)}
                    className={`cursor-pointer hover:bg-slate-50 transition-colors ${selectedSheepId === sheep.id ? 'bg-blue-50/50' : ''}`}
                  >
                    <td className="px-6 py-4 font-medium text-slate-800 flex items-center gap-2">
                      <ScanLine size={14} className="text-slate-400"/> {sheep.tagId}
                    </td>
                    <td className="px-6 py-4 text-slate-600">{sheep.breed}</td>
                    <td className="px-6 py-4 text-slate-600">{sheep.cageId}</td>
                    <td className="px-6 py-4">
                      <span className={`px-2 py-1 rounded text-xs font-medium ${
                        sheep.status === SheepStatus.HEALTHY ? 'bg-green-100 text-green-700' :
                        sheep.status === SheepStatus.SICK ? 'bg-red-100 text-red-700' :
                        'bg-gray-100 text-gray-700'
                      }`}>
                        {sheep.status}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                       <div className="flex justify-end gap-2">
                         <button 
                            onClick={(e) => { e.stopPropagation(); handleOpenEdit(sheep); }}
                            className="p-1 hover:bg-slate-200 rounded text-slate-500"
                         >
                            <Edit size={14} />
                         </button>
                         <button 
                            onClick={(e) => { e.stopPropagation(); handleDelete(sheep.id); }}
                            className="p-1 hover:bg-red-100 rounded text-red-500"
                         >
                            <Trash2 size={14} />
                         </button>
                       </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Detail Panel */}
        <div className="lg:col-span-1 h-full overflow-y-auto">
          {activeSheepData ? (
             <div className="bg-white rounded-xl shadow-sm border border-slate-100 p-6 sticky top-0 space-y-6">
               <div className="flex justify-between items-start">
                 <div>
                   <h2 className="text-2xl font-bold text-slate-800">{activeSheepData.tagId}</h2>
                   <p className="text-slate-500 text-sm">{activeSheepData.breed} • {activeSheepData.gender}</p>
                 </div>
                 <img src={activeSheepData.imageUrl} alt="Sheep" className="w-20 h-20 rounded-lg object-cover bg-slate-200 shadow-sm" />
               </div>

               <div>
                   <h3 className="text-sm font-semibold text-slate-700 mb-2">Weight Growth (kg)</h3>
                   <div className="h-40 bg-slate-50 rounded-lg p-2 border border-slate-100">
                      <ResponsiveContainer width="100%" height="100%">
                        <LineChart data={activeSheepData.weightHistory}>
                           <XAxis dataKey="date" hide />
                           <YAxis hide domain={['dataMin - 2', 'dataMax + 2']} />
                           <Tooltip contentStyle={{fontSize: '12px'}} />
                           <Line type="monotone" dataKey="weight" stroke="#2563eb" strokeWidth={2} dot={{r: 3}} />
                        </LineChart>
                      </ResponsiveContainer>
                   </div>
               </div>

               <div className="grid grid-cols-2 gap-3 text-sm">
                  <div className="bg-slate-50 p-3 rounded border border-slate-100">
                    <p className="text-slate-500 text-xs uppercase tracking-wide">Birth Date</p>
                    <p className="font-medium">{activeSheepData.dob}</p>
                  </div>
                  <div className="bg-slate-50 p-3 rounded border border-slate-100">
                    <p className="text-slate-500 text-xs uppercase tracking-wide">Market Value</p>
                    <p className="font-medium text-green-600">Rp {activeSheepData.marketValue?.toLocaleString()}</p>
                  </div>
                  <div className="bg-slate-50 p-3 rounded border border-slate-100">
                    <p className="text-slate-500 text-xs uppercase tracking-wide">Location</p>
                    <p className="font-medium">{activeSheepData.cageId}</p>
                  </div>
                   <div className="bg-slate-50 p-3 rounded border border-slate-100">
                    <p className="text-slate-500 text-xs uppercase tracking-wide">Last Check</p>
                    <p className="font-medium">2 days ago</p>
                  </div>
               </div>

               {activeSheepData.notes && (
                 <div className="bg-yellow-50 p-4 rounded-lg text-sm text-yellow-800 border border-yellow-200">
                   <strong className="block mb-1">Vet Notes:</strong>
                   {activeSheepData.notes}
                 </div>
               )}

               <button className="w-full py-2.5 bg-slate-800 text-white rounded-lg text-sm font-medium hover:bg-slate-900 transition-colors">
                 Generate Health Report
               </button>
             </div>
          ) : (
            <div className="bg-slate-50 border-2 border-dashed border-slate-200 rounded-xl h-full flex flex-col items-center justify-center text-slate-400 p-8">
               <ScanLine size={48} className="mb-4 opacity-30"/>
               <p className="text-center font-medium">Select a sheep to view details</p>
            </div>
          )}
        </div>
      </div>

      {/* Add/Edit Modal */}
      <Modal 
        isOpen={isModalOpen} 
        onClose={() => setIsModalOpen(false)}
        title={editMode ? 'Edit Sheep' : 'Register New Sheep'}
      >
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Tag ID</label>
              <input 
                required
                className="w-full p-2 border border-slate-200 rounded-lg text-sm" 
                value={formData.tagId || ''}
                onChange={e => setFormData({...formData, tagId: e.target.value})}
                placeholder="AF-XXX"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Breed</label>
              <select 
                 className="w-full p-2 border border-slate-200 rounded-lg text-sm"
                 value={formData.breed || 'Merino'}
                 onChange={e => setFormData({...formData, breed: e.target.value})}
              >
                <option value="Merino">Merino</option>
                <option value="Dorper">Dorper</option>
                <option value="Garut">Garut</option>
                <option value="Suffolk">Suffolk</option>
              </select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
             <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Gender</label>
              <select 
                 className="w-full p-2 border border-slate-200 rounded-lg text-sm"
                 value={formData.gender || 'Male'}
                 onChange={e => setFormData({...formData, gender: e.target.value as any})}
              >
                <option value="Male">Male</option>
                <option value="Female">Female</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Date of Birth</label>
              <input 
                type="date"
                required
                className="w-full p-2 border border-slate-200 rounded-lg text-sm" 
                value={formData.dob || ''}
                onChange={e => setFormData({...formData, dob: e.target.value})}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Status</label>
               <select 
                 className="w-full p-2 border border-slate-200 rounded-lg text-sm"
                 value={formData.status || SheepStatus.HEALTHY}
                 onChange={e => setFormData({...formData, status: e.target.value as any})}
              >
                {Object.values(SheepStatus).map(s => <option key={s} value={s}>{s}</option>)}
              </select>
            </div>
             <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Cage</label>
              <input 
                className="w-full p-2 border border-slate-200 rounded-lg text-sm" 
                value={formData.cageId || ''}
                onChange={e => setFormData({...formData, cageId: e.target.value})}
                placeholder="e.g. CAGE-A"
              />
            </div>
          </div>

          <div>
             <label className="block text-sm font-medium text-slate-700 mb-1">Notes</label>
             <textarea 
               className="w-full p-2 border border-slate-200 rounded-lg text-sm"
               rows={3}
               value={formData.notes || ''}
               onChange={e => setFormData({...formData, notes: e.target.value})}
             />
          </div>

          <div className="pt-2 flex gap-3">
            <button 
              type="button" 
              onClick={() => setIsModalOpen(false)}
              className="flex-1 py-2 border border-slate-200 rounded-lg text-sm font-medium hover:bg-slate-50"
            >
              Cancel
            </button>
            <button 
              type="submit" 
              className="flex-1 py-2 bg-agri-600 text-white rounded-lg text-sm font-medium hover:bg-agri-700"
            >
              {editMode ? 'Save Changes' : 'Add Sheep'}
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
};