// Translations for multi-language support
export const TRANSLATIONS = {
  EN: {
    dashboard: "Dashboard",
    sheep: "Sheep Management",
    investments: "Investments",
    marketplace: "Marketplace",
    cctv: "Live CCTV",
    qurban: "Tabung Qurban",
    logout: "Logout",
    welcome: "Welcome back",
    totalAssets: "Total Assets",
    activeSheep: "Active Sheep",
    healthAlerts: "Health Alerts",
    profit: "Net Profit",
    viewAll: "View All",
    search: "Search...",
    buyNow: "Buy via WhatsApp",
    growthChart: "Growth Chart",
    askAi: "Ask Farm AI",
  },
  ID: {
    dashboard: "Dasbor",
    sheep: "Manajemen Domba",
    investments: "Investasi",
    marketplace: "Pasar",
    cctv: "CCTV Langsung",
    qurban: "Tabung Qurban",
    logout: "Keluar",
    welcome: "Selamat datang kembali",
    totalAssets: "Total Aset",
    activeSheep: "Domba Aktif",
    healthAlerts: "Peringatan Kesehatan",
    profit: "Laba Bersih",
    viewAll: "Lihat Semua",
    search: "Cari...",
    buyNow: "Beli via WhatsApp",
    growthChart: "Grafik Pertumbuhan",
    askAi: "Tanya AI Farm",
  },
};
