/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSheepRouteImport } from './routes/_auth.sheep'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthQurbanRouteImport } from './routes/_auth.qurban'
import { Route as AuthMarketplaceRouteImport } from './routes/_auth.marketplace'
import { Route as AuthInvestmentsRouteImport } from './routes/_auth.investments'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthCctvRouteImport } from './routes/_auth.cctv'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSheepRoute = AuthSheepRouteImport.update({
  id: '/sheep',
  path: '/sheep',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthQurbanRoute = AuthQurbanRouteImport.update({
  id: '/qurban',
  path: '/qurban',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMarketplaceRoute = AuthMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInvestmentsRoute = AuthInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCctvRoute = AuthCctvRouteImport.update({
  id: '/cctv',
  path: '/cctv',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cctv': typeof AuthCctvRoute
  '/dashboard': typeof AuthDashboardRoute
  '/investments': typeof AuthInvestmentsRoute
  '/marketplace': typeof AuthMarketplaceRoute
  '/qurban': typeof AuthQurbanRoute
  '/settings': typeof AuthSettingsRoute
  '/sheep': typeof AuthSheepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/cctv': typeof AuthCctvRoute
  '/dashboard': typeof AuthDashboardRoute
  '/investments': typeof AuthInvestmentsRoute
  '/marketplace': typeof AuthMarketplaceRoute
  '/qurban': typeof AuthQurbanRoute
  '/settings': typeof AuthSettingsRoute
  '/sheep': typeof AuthSheepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/cctv': typeof AuthCctvRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/investments': typeof AuthInvestmentsRoute
  '/_auth/marketplace': typeof AuthMarketplaceRoute
  '/_auth/qurban': typeof AuthQurbanRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/sheep': typeof AuthSheepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cctv'
    | '/dashboard'
    | '/investments'
    | '/marketplace'
    | '/qurban'
    | '/settings'
    | '/sheep'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/cctv'
    | '/dashboard'
    | '/investments'
    | '/marketplace'
    | '/qurban'
    | '/settings'
    | '/sheep'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/cctv'
    | '/_auth/dashboard'
    | '/_auth/investments'
    | '/_auth/marketplace'
    | '/_auth/qurban'
    | '/_auth/settings'
    | '/_auth/sheep'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sheep': {
      id: '/_auth/sheep'
      path: '/sheep'
      fullPath: '/sheep'
      preLoaderRoute: typeof AuthSheepRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/qurban': {
      id: '/_auth/qurban'
      path: '/qurban'
      fullPath: '/qurban'
      preLoaderRoute: typeof AuthQurbanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/marketplace': {
      id: '/_auth/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthMarketplaceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/investments': {
      id: '/_auth/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof AuthInvestmentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/cctv': {
      id: '/_auth/cctv'
      path: '/cctv'
      fullPath: '/cctv'
      preLoaderRoute: typeof AuthCctvRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthCctvRoute: typeof AuthCctvRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthInvestmentsRoute: typeof AuthInvestmentsRoute
  AuthMarketplaceRoute: typeof AuthMarketplaceRoute
  AuthQurbanRoute: typeof AuthQurbanRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSheepRoute: typeof AuthSheepRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCctvRoute: AuthCctvRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthInvestmentsRoute: AuthInvestmentsRoute,
  AuthMarketplaceRoute: AuthMarketplaceRoute,
  AuthQurbanRoute: AuthQurbanRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSheepRoute: AuthSheepRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
